apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: mimir
    namespace: argocd
finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
      name: ''
      namespace: mimir
      server: 'https://kubernetes.default.svc'
  source:
      path: ''
      repoURL: 'https://grafana.github.io/helm-charts'
      targetRevision: '5.4.0'
      chart: mimir-distributed
  sources: []
  project: default
  syncPolicy:
      automated:
          prune: true
          selfHeal: true
      retry:
          limit: 2
          backoff:
              duration: 5s
              maxDuration: 3m0s
              factor: 2
      syncOptions:
          - CreateNamespace=true
